name: Comment Actions
on:
  issue_comment:
  workflow_dispatch:
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/gfi')
    runs-on: ubuntu-latest
    steps:
    - name: See Payload
      run: echo "PAYLOAD:\n${PAYLOAD}"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}

    - name: Install Dependencies
      run: pip install ghapi

    - name: Add Label
      shell: python
      run: |
        import os
        from ghapi.core import GhApi
        owner, repo = os.environ['REPO'].split('/')
        api = GhApi(owner=owner, repo=repo)
        api.issues.add_labels(issue_number=os.environ['NUMBER'], labels=['goodfirstissue'])
      env:
        NUMBER: ${{ github.event.issue.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
