name: Smoke Test Workflow
on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        def add_numbers(a, b):
          return a + b
        assert add_numbers(2, 3) == 5, "Error from assertion"
        assert add_numbers(1, -1) == 0, "Error from assertion"
        assert add_numbers(0, 0) == 0, "Error from assertion"
        assert add_numbers(2.5, 3.5) == 6.0, "Error from assertion"
      shell: python
